### PR TITLE
chore: upgrade strapi and related dependencies, remove pleb config

### PR DESCRIPTION
**Pull request by matangeorgi**
Upgrade Strapi and its plugins to the latest versions, ensuring compatibility and improved features. Remove the pleb configuration.

### CODE REVIEW

**Review by noammu — COMMENTED** [review]
I see errors in these files:
- `data-api.tsx`
- `footer.tsx`
- `about/route.tsx`
Are they ok? They do not appear in `main`.

Unfortunately this is happening also in `main` but still:
Do we want an About page with nothing in it? 
Also clicking on Contact opens nothing on browser. 
And clicking on Projects does nothing.

**Comment by matangeorgi** [comment]
> I see errors in these files:
> 
> * `data-api.tsx`
> * `footer.tsx`
> * `about/route.tsx`
>   Are they ok? They do not appear in `main`.
> 
> Unfortunately this is happening also in `main` but still: Do we want an About page with nothing in it? Also clicking on Contact opens nothing on browser. And clicking on Projects does nothing.

is it a regression? if not, then lets open an issue about it but lets not include it in this pr, as im not trying to fix issues here.

**Comment by noammu** [comment]
It is a regression.

**Review by noammu — COMMENTED** [review]
Still there are some Typescript stuff, slacked to Matan

**Review by noammu — COMMENTED** [review]
Try to open under `Projects` the `Desert Modernism Oasis` 😢

**Review by noammu — APPROVED** [review]
Woohoo approved! 🥳

**Pull request merged**
